import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import React from "react";
import LeftNav from "@/components/LeftNav";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Next App template',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
            <div className="h-screen flex flex-row m-0">
                <div className={"dark:border-amber-50 border-2 rounded-3xl"}>
                    <LeftNav />
                </div>
                <div className={"w-full flex flex-col dark:border-amber-50 border-2 rounded-3xl"}>
                    <div>
                    {/*<Header />*/}
                    </div>
                    <div>
                    {children}
                    </div>
                </div>

            </div>
            </body>
        </html>
    )
}
